sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "gUU8Px1zqyuKM8cfVsPHy770RM+bY43p+9zQEtVe9ZQrixJ//gNQ/d0HVDkM4MCNaC2PnM/vt1VICmv8AU22MyENVTDtppPeQK20FVY85FRiuf6tpLBnBqJJMoiQVxU6H7iikSu/oJZZzuLvvun1UfQJBw6v0HXG1iSq/mEOpbWki79uxrbeqLuOPPnA0AfQMQVDwUK7HL64qFPn2eUdOxUwNKd3YpHe4mYClwFkhA6XtWZKOLeekgBe9zWLLfPV62uOyh3o4XT/6a0JZXsjcE96SbrZVClLApKYRYXdNAAcxhhFes1OrTV+RD8WhGDAPXdlUFIljjp3mRGiT7m5/0ttGQogww58bS5Mt8ak5EPzx85kGZwZLBDzFyAvTJzCbeoME6gHIfbJOagc5x/hKVDSPCeYHnX9j++m4GVfHetACbgsfMC+hTu12INjqE2iJgURsWOMBEyihQv96LntxmBfVudovuWtSp/xwQ+wCSUpDWuPdN+F1cpbXYXHNUph0GUmDzzVWiR97fKr00IhtUfTC+uL58P2LdLimCFQi4o1pwaY/vSEAAMrQxh/+g7NstZoFZRK09v/Ucpg3LzjAuz1SyRgFi9ffAP2FQ/Wz7PVd2W92QvSHFu5pw7YQYQr0Sb0QgxiVJ2DNfYYSo9ISWnFccQG6e7XwG/1+ja9uOg="
  - secure: "c2lVCRGnWzmrOxV5HOR4nHqc/0mP6dJ+3OhFDkWSc65zlv0J39A7jshY3AhkveZJD8dFDAnLe44IXTD5qZtK8lLJfOnPwChfZCHu1I1ohoDE/k7Kcy0o8GWidxSt7DaJGiiZRr7u0NRnYW/nyLcstLNm0C+Ua0WtYCJRoLJz2CvLLFAa/8hk+fFh6GO/qgEMwfM3bwNSdWRokfYY5Ide4RmZOf701dMP4dTFJmX7OswBL7F6UHtM2ESD9lUvTG2pKtiLAT6J7P8DPJcMEDFUWcGj5v0HI6Wk8ssygQFt3WhRJYDH2JBbJhtiaagE2ULDbuQsxElsbJ9zDOEmbi+mw7EmxhuhUPGDAFU90M1t4rCrc8shSUFM+jfAK1crWSzwP4gqVWEbl7QCN0IpNkGA8krF5NpknEfGaSQGQwY3otc+Phw3HGQc3y+U9aXUuKZNHmJE+90nTPTv9uNHZxNFxCpzuhn//5jYj17Hie7iUuHivxmtZkT7tWP8+3unI9oS10rDgUshpiUBsFf4D1sTe2YfaY9aAhXGFLLnVc+GGIhkG1SxkOFlSw5UuadvQh2leEb2v9aom4aH3yWZmR6ltEN3XbI7izKVoy+mZ6YeuvrUpoGPBJeVL8+m+WzpTQcmko3HpqrUx6jHeUW5TbtaNgRVbeOEK6tiiIDWLTs+2fg="
  - secure: "Y9aC+qVMKbkg53B8RaZeu+qOrzqeLljPwRjkbjjLgtqFl9ZZhYX7uzgUFej6bIK3bWQ0TaFF/bf6zS02V14CGa00BPjzKM4imFBl0im2Y7xlCOZY+NkikuStI4RI4J9v0d+3mPc4pHodvI2XaxPs+baDrCYcFro+8hHUQOYcwpL74krFBat0+L7+jcjTuY64FTgpuMfHgr6BYedG6m6qOWZazK6u194eD4ZduTi9wg2Ok6vPfUHi9uiMcWU0GasacgKguDHnwC5KzrR9M+jotspGSOX/7WcpDYuymtUKO6T6lguP3DuKtfHNZEYuxQjnXnBkQ0ulEoHr1rIzh1YyYA3dW1r1yNqGDT45dOcmagrfTJh5+qOqy4EnFW10n6cXgFudEJWhy97KYk+5lA+rS0mk6wkV2P6BjV5EIrFzWlJ+x3CuWhPcvMikl0h6ICYB2ye5SeLeCQkQvzIt8LE4fLBH4VxhPUu54ENR/cSl3A74HSghOSRxdQJpzjLU4KaSkiaIfuqY2ida0iYX1WaaZaklRMzTL8hhvv++poMJeC64ephDGjKaVL+6a1PR/Y8j1A6rXuZKsSL+/+tXoP1RIkDVbStBxpee9uh3saQnptrvWKKB3fQletq1N97l6D3pHdyRZZTQx7SDIQ0CjZ4eMmHB3E3r99pui8TtMd/V07g="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
